### ISSUE TITLE
2) Establish common templates for generated projects

### ISSUE THREAD

**Issue by obuckley-kenzan** [kenzanlabs/generator-keystone#2]
a) project dotfiles (gitignore, gitattributes, .editorconfig, .yo-rc.json
b) package.json
c) bower.json
d) CONTRIBUTING.md
e) README.md

should include unit tests

Things to ask:

- Project Name
- Project Description

- Maybe for bower.json and package.json, it would be better to have Yeoman run `bower init` and `npm init` (respectively) instead, based on use input (eg. do you want bower, do you want npm?)

cc: @paul-barry-kenzan

**Comment by paul-barry-kenzan** [comment]
@thescientist13 
Is this closed by #15?

**Comment by thescientist13** [comment]
looks like it.  good catch!
