### ISSUE TITLE
Fatal error when running generator

### ISSUE THREAD

**Issue by paul-barry-kenzan** [kenzanlabs/generator-keystone#20]
When running the generator (using the corrected SHA from #19), Yeoman throws the following fatal error:

```bash
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/index.js:164:45)
    at prompting (/usr/local/lib/node_modules/generator-keystone/app/index.js:218:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/index.js:392:23)
    at /usr/local/lib/node_modules/generator-keystone/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-keystone/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/index.js:393:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by paul-barry-kenzan** [comment]
I was able to resolve this by updating my global Yeoman version from 1.7.0 to 1.8.5. Not sure how to best handle this type of requirement. 

Related issues on GitHub:
- https://github.com/FountainJS/generator-fountain-webapp/issues/56
- https://github.com/yeoman/generator-generator/issues/160

**Comment by thescientist13** [comment]
do we need to document this in the README?  minimum system requirements, etc?

**Comment by paul-barry-kenzan** [comment]
Yeah, seems that something like that will be required. I looked into the Yeoman docs and don't see anything about enforcing a global version.

**Comment by thescientist13** [comment]
maybe it's an with the version of NodeJS you're running?

**Comment by thescientist13** [comment]
good to close or still want to leave this open @paul-barry-kenzan ?

**Comment by paul-barry-kenzan** [comment]
@thescientist13 
With #21 being merged, we're good to close this.
